version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    target_branch: dependency/dependabot
    schedule:
      interval: daily
    assignees:
      - ChristophShyper
    labels:
      - automatic

  # Enable version updates for Docker
  - package-ecosystem: docker
    directory: "/"
    target_branch: dependency/dependabot
    schedule:
      interval: daily
    assignees:
      - ChristophShyper
    labels:
      - automatic

  # Enable version updates for pip
  - package-ecosystem: pip
    directory: "/pip/common/"
    target_branch: dependency/dependabot
    schedule:
      interval: daily
    assignees:
      - ChristophShyper
    labels:
      - automatic

  # Enable version updates for pip
  - package-ecosystem: pip
    directory: "/pip/aws/"
    target_branch: dependency/dependabot
    schedule:
      interval: daily
    assignees:
      - ChristophShyper
    labels:
      - automatic
